image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
- port: 3000
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    echo "";
    echo "Welcome to the TEC2020 Workshop environment. Useful commands are:";
    echo "/juice-shop/deploy.sh";
    echo "The code is located in /juice-shop/juice-shop/";
- name: Apache
  command: >
    whoami
    ls
