image:
  file: .gitpod.dockerfile
  context: juice-shop
ports:
- port: 8080
  onOpen: open-preview
- port: 3000
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    echo "";
    echo "Welcome to the TEC2020 Workshop environment. Useful commands are:";
    echo "/juice-shop/deploy.sh";
    echo "The code is located in /juice-shop/juice-shop/";
- name: Terminal 2
  command: rm -rf /workspace/TEC2020/juice-shop && ln -s /juice-shop /workspace/TEC2020/ && ls && clear
    
